version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - typesense
    networks:
      - laravel
  web:
    image: 'nginx:latest'
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
      - db
    networks:
      - laravel
  db:
    image: 'postgres:16'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nowty
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - laravel
  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    networks:
      - laravel
networks:
  laravel:
