services:
  - type: web
    name: app
    env: docker
    healthCheckPath: / # replace with your health check endpoint
    buildCommand: docker build -t app:latest .
    startCommand: docker run -p 9000:9000 app:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
  - type: web
    name: web
    env: docker
    healthCheckPath: /
    buildCommand: docker build -t web:latest -f Dockerfile.nginx .
    startCommand: docker run -p 8080:80 web:latest

databases:
  - name: db
    engine: POSTGRESQL
    version: 11

  - type: web
    name: typesense
    env: docker
    healthCheckPath: /
    dockerfilePath: Dockerfile.typesense
    buildCommand: docker build -t typesense:latest -f Dockerfile.typesense .
    startCommand: docker run -p 8108:8108 typesense:latest
